import { Agent } from "./types";

export const AGENTS: Agent[] = [
  {
    id: "coach",
    name: "Coach",
    emoji: "\ud83d\udcaa",
    workspace: "personal",
    role: "Salud, ejercicio y nutrici\u00f3n",
    model: "anthropic/claude-sonnet-4-5",
    channel: "telegram",
    botHandle: "@coachtomas_bot",
    color: "#E8593C",
    status: "online",
    lastActive: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    todayCost: 0.23,
    sessionsToday: 4,
    tokensToday: 6200,
  },
  {
    id: "wolf",
    name: "Wolf",
    emoji: "\ud83d\udc3a",
    workspace: "personal",
    role: "CFO personal / Finanzas",
    model: "anthropic/claude-sonnet-4-6",
    channel: "telegram",
    botHandle: "@wolfCFO_bot",
    color: "#EF9F27",
    status: "idle",
    lastActive: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    todayCost: 0.41,
    sessionsToday: 6,
    tokensToday: 11400,
  },
  {
    id: "pilot",
    name: "Pilot",
    emoji: "\ud83e\udded",
    workspace: "personal",
    role: "Productividad y agenda",
    model: "anthropic/claude-sonnet-4-5",
    channel: "telegram",
    botHandle: "pendiente",
    color: "#888780",
    status: "offline",
    lastActive: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    todayCost: 0,
    sessionsToday: 0,
    tokensToday: 0,
  },
  {
    id: "chief",
    name: "Chief",
    emoji: "\ud83d\udc51",
    workspace: "cnbx",
    project: "holding",
    role: "COO del holding",
    model: "anthropic/claude-opus-4-6",
    fallback: "anthropic/claude-sonnet-4-6",
    channel: "telegram",
    botHandle: "@TomexIA_bot",
    color: "#7F77DD",
    status: "online",
    lastActive: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    todayCost: 1.87,
    sessionsToday: 14,
    tokensToday: 28500,
  },
  {
    id: "north",
    name: "North",
    emoji: "\ud83c\udfd7\ufe0f",
    workspace: "cnbx",
    project: "arquitex",
    role: "CMO / Estrategia",
    model: "anthropic/claude-sonnet-4-6",
    fallback: "anthropic/claude-opus-4-6",
    channel: "telegram",
    botHandle: "@north_cnbx_bot",
    color: "#D4537E",
    status: "busy",
    lastActive: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    todayCost: 0.94,
    sessionsToday: 8,
    tokensToday: 18200,
  },
  {
    id: "lauri",
    name: "Lauri",
    emoji: "\ud83d\ude80",
    workspace: "cnbx",
    project: "arquitex",
    role: "CTO / Launcher",
    model: "anthropic/claude-sonnet-4-6",
    fallback: "anthropic/claude-opus-4-6",
    channel: "telegram",
    botHandle: "@lauri_cnbx_bot",
    color: "#E8593C",
    status: "online",
    lastActive: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    todayCost: 0.72,
    sessionsToday: 9,
    tokensToday: 14800,
  },
  {
    id: "engine",
    name: "Engine",
    emoji: "\u2699\ufe0f",
    workspace: "cnbx",
    project: "blackfin",
    role: "Ops Lead",
    model: "anthropic/claude-sonnet-4-6",
    fallback: "anthropic/claude-opus-4-6",
    channel: "telegram",
    botHandle: "@engine_cnbx_bot",
    color: "#1D9E75",
    status: "idle",
    lastActive: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    todayCost: 0.38,
    sessionsToday: 5,
    tokensToday: 8900,
  },
];

export function getAgent(id: string): Agent | undefined {
  return AGENTS.find((a) => a.id === id);
}

export function getAgentsByWorkspace(workspace: string): Agent[] {
  return AGENTS.filter((a) => a.workspace === workspace);
}

export function getAgentsByProject(project: string): Agent[] {
  return AGENTS.filter((a) => a.project === project);
}
