import type { Task, ActivityEvent } from "./types";

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Analizar m\u00e9tricas de febrero Arquitex",
    description: "Revisar CPL, reuniones agendadas, tasa de cierre. Comparar con enero y proponer ajustes para marzo.",
    assignee: "north",
    project: "arquitex",
    workspace: "cnbx",
    status: "in_progress",
    priority: "high",
    created: "2026-03-10T09:00:00-03:00",
    updated: "2026-03-15T11:20:00-03:00",
  },
  {
    id: "t2",
    title: "Deploy landing page v2",
    description: "Subir la nueva versi\u00f3n de la landing con testimonios y CTA actualizado.",
    assignee: "lauri",
    project: "arquitex",
    workspace: "cnbx",
    status: "review",
    priority: "high",
    created: "2026-03-12T14:00:00-03:00",
    updated: "2026-03-15T09:45:00-03:00",
  },
  {
    id: "t3",
    title: "Configurar pipeline de onboarding",
    description: "Automatizar el flujo de nuevos clientes: formulario \u2192 n8n \u2192 Supabase \u2192 notificaci\u00f3n.",
    assignee: "engine",
    project: "blackfin",
    workspace: "cnbx",
    status: "todo",
    priority: "medium",
    created: "2026-03-14T10:00:00-03:00",
    updated: "2026-03-14T10:00:00-03:00",
  },
  {
    id: "t4",
    title: "Revisar presupuesto Q2",
    description: "Proyectar costos de API, hosting y herramientas para el pr\u00f3ximo trimestre.",
    assignee: "chief",
    project: "holding",
    workspace: "cnbx",
    status: "backlog",
    priority: "medium",
    created: "2026-03-13T08:00:00-03:00",
    updated: "2026-03-13T08:00:00-03:00",
  },
  {
    id: "t5",
    title: "Crear contenido para redes Arquitex",
    description: "3 posts para Instagram y 1 art\u00edculo para LinkedIn sobre construcci\u00f3n sustentable.",
    assignee: "north",
    project: "arquitex",
    workspace: "cnbx",
    status: "todo",
    priority: "low",
    created: "2026-03-14T16:00:00-03:00",
    updated: "2026-03-14T16:00:00-03:00",
  },
  {
    id: "t6",
    title: "Setup monitoring de uptime",
    description: "Configurar alertas de uptime para todos los servicios en el VPS.",
    assignee: "engine",
    project: "blackfin",
    workspace: "cnbx",
    status: "in_progress",
    priority: "medium",
    created: "2026-03-11T11:00:00-03:00",
    updated: "2026-03-15T08:30:00-03:00",
  },
  {
    id: "t7",
    title: "Armar plan de ejercicio semanal",
    description: "Rutina de 4 d\u00edas adaptada al horario actual. Incluir calentamiento y estiramientos.",
    assignee: "coach",
    workspace: "personal",
    status: "done",
    priority: "medium",
    created: "2026-03-09T07:00:00-03:00",
    updated: "2026-03-14T18:00:00-03:00",
  },
  {
    id: "t8",
    title: "Revisar gastos de tarjeta febrero",
    description: "Categorizar gastos, identificar suscripciones innecesarias, calcular tasa de ahorro.",
    assignee: "wolf",
    workspace: "personal",
    status: "todo",
    priority: "high",
    created: "2026-03-01T08:00:00-03:00",
    updated: "2026-03-12T10:00:00-03:00",
  },
  {
    id: "t9",
    title: "SEO audit Arquitex website",
    description: "Revisar meta tags, velocidad, Core Web Vitals. Generar reporte con quick wins.",
    assignee: "lauri",
    project: "arquitex",
    workspace: "cnbx",
    status: "backlog",
    priority: "low",
    created: "2026-03-15T10:00:00-03:00",
    updated: "2026-03-15T10:00:00-03:00",
  },
];

const now = Date.now();
const min = 60 * 1000;

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: "e1",
    timestamp: new Date(now - 1 * min).toISOString(),
    agentId: "north",
    action: "Analizando datos de campa\u00f1a Google Ads febrero",
    type: "thinking",
  },
  {
    id: "e2",
    timestamp: new Date(now - 3 * min).toISOString(),
    agentId: "chief",
    action: "Respondi\u00f3 consulta sobre estructura holding",
    type: "reply",
  },
  {
    id: "e3",
    timestamp: new Date(now - 5 * min).toISOString(),
    agentId: "lauri",
    action: "Deploy completado: landing-v2 en Vercel",
    type: "alert",
  },
  {
    id: "e4",
    timestamp: new Date(now - 8 * min).toISOString(),
    agentId: "lauri",
    action: "Guard\u00f3 en memoria: configuraci\u00f3n DNS Arquitex",
    type: "memory",
  },
  {
    id: "e5",
    timestamp: new Date(now - 12 * min).toISOString(),
    agentId: "coach",
    action: "Envi\u00f3 rutina de ejercicio para hoy",
    type: "reply",
  },
  {
    id: "e6",
    timestamp: new Date(now - 15 * min).toISOString(),
    agentId: "engine",
    action: "Ejecutando health check en todos los servicios",
    type: "subagent",
  },
  {
    id: "e7",
    timestamp: new Date(now - 20 * min).toISOString(),
    agentId: "north",
    action: "Guard\u00f3 en memoria: m\u00e9tricas CPL febrero",
    type: "memory",
  },
  {
    id: "e8",
    timestamp: new Date(now - 30 * min).toISOString(),
    agentId: "engine",
    action: "Configuraci\u00f3n de monitoring actualizada",
    type: "reply",
  },
  {
    id: "e9",
    timestamp: new Date(now - 45 * min).toISOString(),
    agentId: "wolf",
    action: "Respondi\u00f3 an\u00e1lisis de gastos tarjeta",
    type: "reply",
  },
  {
    id: "e10",
    timestamp: new Date(now - 60 * min).toISOString(),
    agentId: "chief",
    action: "Deleg\u00f3 tarea a North: an\u00e1lisis de m\u00e9tricas",
    type: "subagent",
  },
  {
    id: "e11",
    timestamp: new Date(now - 90 * min).toISOString(),
    agentId: "chief",
    action: "Guard\u00f3 en memoria: decisi\u00f3n sobre prioridades Q2",
    type: "memory",
  },
  {
    id: "e12",
    timestamp: new Date(now - 120 * min).toISOString(),
    agentId: "lauri",
    action: "Subagente: ejecutando tests de integraci\u00f3n",
    type: "subagent",
  },
];
